[paths]
base_dir = "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector"
output_dir = "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector\\output"
select_csv_reverse_file = ""
select_csv_output_reverse_dir = ""
select_markdown_reverse_file = ""
select_markdown_output_reverse_dir = []
path_style = "windows"

[files]
ignored_extensions = [ ".exe", ".dll",]
ignored_files = [ "file_to_ignore.txt",]

[directories]
ignored_directories = [ "dir_to_ignore",]

[file_specific]
use_file_specific = false
specific_files = [ "",]

[output]
markdown_file_prefix = "Full_Project"
csv_file_prefix = "Detailed_Project"

[metrics]
size_unit = "KB"

[presets]
preset-1 = [ "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/settings_frame.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/main.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/extraction_frame.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/file_specific_frame.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/theme_manager.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/settings_manager.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/constants.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/extraction_worker.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/header_frame.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/extractorz.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/__init__.py", "E:/_Development_/DEVELOPMENT/Rewnozom-github/llm_module_extractor_collector/gui/main_window.py",]
current_preset = "preset-1"
