[paths]
base_dir = ""
output_dir = ""
select_csv_reverse_file = ""
select_csv_output_reverse_dir = ""
select_markdown_reverse_file = ""
select_markdown_output_reverse_dir = []
path_style = "windows"

[files]
ignored_extensions = [ ".exe", ".dll",]
ignored_files = [ "file_to_ignore.txt",]

[directories]
ignored_directories = [ "dir_to_ignore",]

[file_specific]
use_file_specific = false
specific_files = [ "",]

[output]
markdown_file_prefix = "Full_Project"
csv_file_prefix = "Detailed_Project"

[metrics]
size_unit = "KB"

[presets]
preset-1 = []
